language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - lerna bootstrap
  - npm run test:ci

before_deploy:
  - npm install netlify-cli -g
  - npm run build
  - echo "APP_URL=$APP_URL" >> .env
  - echo "BC_AUTH_CALLBACK=$BC_AUTH_CALLBACK" >> .env
  - echo "BC_CLIENT_ID=$BC_CLIENT_ID" >> .env
  - echo "BC_CLIENT_SECRET=$BC_CLIENT_SECRET" >> .env
  - echo "FAUNADB_SERVER_SECRET=$FAUNADB_SERVER_SECRET" >> .env
  - cat .env

deploy:
  - provider: script
    script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN --prod --message "$TRAVIS_COMMIT_MESSAGE" --functions packages/functions-netlify/build --dir packages/app/build
    skip_cleanup: true
    on:
      branch: master
