language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - lerna bootstrap
  - npm run test:ci

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  - provider: script
    script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN --prod message $TRAVIS_COMMIT_MESSAGE
    skip_cleanup: true
    on:
      branch: master
